version: "3.9"
services:
  wikigpt:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - 80
    volumes:
      - .:/usr/local/isudha/wikigpt
    stdin_open: true
    tty: true
    command: bash -c "python3 manage.py runserver --insecure 0.0.0.0:80"
    environment:
      - CURR_ENV=prod
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
